apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongodb-secret
  namespace: app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: mongodb-secret
    creationPolicy: Owner
  data:
    - secretKey: MONGO_USERNAME
      remoteRef:
        key: dev/mongodb
        property: username
    - secretKey: MONGO_PASSWORD
      remoteRef:
        key: dev/mongodb
        property: password
