apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mongodb-secret
  namespace: app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore

  target:
    name: mongodb-secret
    creationPolicy: Owner

  data:
    - secretKey: MONGO_USERNAME
      remoteRef:
        key: app/mongodb
        property: username

    - secretKey: MONGO_PASSWORD
      remoteRef:
        key: app/mongodb
        property: password