apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vpn-secrets
  namespace: app
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: vpn-secrets
    creationPolicy: Owner

  data:
    - secretKey: client-key
      remoteRef:
        key: vpn/client/private-key

    - secretKey: server-key
      remoteRef:
        key: vpn/server/private-key