persistence:
  storageClass: gp3

controller:
  admin:
    username: admin
    password: admin123
#     password:    "${JENKINS_ADMIN_PASSWORD}"



  serviceType: ClusterIP

  # =========================================================
  # SECURITY WARNING:
  # Docker socket gives full node access.
  # Use only in dev/staging, NOT production.
  # =========================================================

  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
        type: Socket

    - name: docker-bin
      hostPath:
        path: /usr/bin/docker
        type: File

  volumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock

    - name: docker-bin
      mountPath: /usr/bin/docker